# Generated by Django 3.2.12 on 2023-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmeli', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('lastname', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('gender', models.CharField(choices=[('1', 'پسر'), ('2', 'دختر')], max_length=6, verbose_name='جنسیت')),
            ],
            options={
                'verbose_name': 'شرکت کننده',
                'verbose_name_plural': 'شرکت کنندگان',
            },
        ),
    ]
